### ISSUE TITLE
Disks : get hardware disks really connected to the host, not just the one we detect from the partition table

### ISSUE THREAD

**Issue by bpetit** [Boavizta/boagent#12]
# Problem / Use case

We detect disks from the partition table, but this could hide hardware if there is either a software or an hardware RAID

# Solution

Scan for devices in /dev or /sys/bock and categorize them

**Comment by bpetit** [comment]
cc @neywat

**Comment by neywat** [comment]
Searching for all drives, bailing out "/boot" associated drive lookup. Removing the need for /proc/partitions parsing.
