### ISSUE TITLE
Cpus : fix or replace py-cpuinfo to get the number of hard CPUs / sockets on a multi socket machine

### ISSUE THREAD

**Issue by bpetit** [Boavizta/boagent#13]
### Problem / Use case

We use py-cpuinfo which apparently doesn't make a difference between mono socket and multi socket MB

### Solution

We could either find another lib, or create a PR for py-cpuinfo to fix this.

**Comment by benjaminlebigot** [comment]
Hey, Do you think that lstopo could do the job ?

**Comment by benjaminlebigot** [comment]
By myself ? Nope but it looks like it does the job : https://www.open-mpi.org/projects/hwloc/ | https://linux.die.net/man/7/hwloc

If you have a use case or a machine with an ssh connection having multii-socket on its motherboard, I can test it for you, it is really not complicated/long to do.

Tell me if you have some time to spend/to discuss about this point and the needs for the agent, I would gladly contribute to such issue.

**Comment by benjaminlebigot** [comment]
Hi @bpetit,

I started to work on the contribution on py-cpuinfo in order to retrieve the socket_count.

Here is the current pull request: https://github.com/workhorsy/py-cpuinfo/pull/172
I will update the `/hardware/cpu/cpu.py` once the pull request is accepted.

**Comment by benjaminlebigot** [comment]
Since we don't have any answer from the MR below, I added a function to get the nb of socket in the hardware/cpu.py file
You can find this work on the add_socket_number branch.

I will start an MR
