### ISSUE TITLE
Upgrade to the latest version of the boaviztapi 0.1.3 or 0.2

### ISSUE THREAD

**Issue by bpetit** [Boavizta/boagent#24]
Usage of hours_electrical_consumption had some issues that have been fixed, we need to integrate those fixes.

**Comment by da-ekchajzer** [comment]
I just pushed : 
* docker  image : docker pull ghcr.io/boavizta/boaviztapi:0.1.2 
* pip package : https://pypi.org/project/boaviztapi/
