### ISSUE TITLE
Implement guessing of the usage location if no location is specified

### ISSUE THREAD

**Issue by bpetit** [Boavizta/boagent#25]
To complement, looks like we could guess the location from : 
- geoip based location : https://pytutorial.com/python-get-country-from-ip-python
- or to avoid geoip and its flows we could guess the location from the public ip address as seen from a service like https://ipinfo.io/ then look for whois + traceroute information https://www.atlantic.net/vps-hosting/how-to-find-location-servers-traceroute-whois/

_Originally posted by @bpetit in https://github.com/Boavizta/boagent/issues/23#issuecomment-1158359290_

**Comment by bdromard** [comment]
Currently, there are no solutions to implement automatic geopositioning of an asset with the public IP through a static, local database. Most solutions rest on looking up constantly updated
databases, resolving an IP to a location. These services are RESTful APIs that need an account and a token on the client-side for Python, which do not make them manageable for Boagent.

To follow on this issue, we will have to think on how to ask the client for their location if no location or only the default one (for BoaviztAPI : "EEE") has been set. This could 
represent a warning on the OpenAPI front-end, as an element of the API response, and a feature of Boagent packaged as a CLI tool. We will have to see how BoaviztAPI may evolve on this
issue also.
